### PR TITLE
fix p4est_vtk_write_cell_datav

### PR DESCRIPTION
**Pull request by pkestene**
There is a bug in routine p4est_vtk_write_cell_datav : input variable list is not parsed in a correct way.

the call 
    va_arg (ap, p4est_vtk_context_t *);
checks for the end of variable input list, and must be made after all other item have been parsed.

### CODE REVIEW

**Comment by cburstedde** [comment]
Dear pk,
Can you please check that you have the right to submit the changes under the BSD license?
Then you may add a file doc/author_lastname.txt like the others. Thanks again!

**Comment by pkestene** [comment]
that's ok. Thanks.

**Comment by cburstedde** [comment]
> that's ok. Thanks.

Thanks for your patience, I'll get to it in roughly two weeks.

**Comment by cburstedde** [comment]
Dear P.,
I finally got back to this. I've fixed it in the current master and upstream. Thanks so much for your report!
Carsten

**Pull request closed without merging**
