### PR TITLE
Cmake examples

### PR DESCRIPTION
**Pull request by mkirilin**
This PR simplifies and unifies examples/CMakeLists.txt file.
In addition, it make examples build by default.

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks! is this as much as possible analogous to the libsc code for the examples?

**Comment by mkirilin** [comment]
It is a good balance between simplicity and similarity with the libsc, considering the peculiarities  of p4est (e.g. 2 or 3 dimensions, etc.)

**Comment by cburstedde** [comment]
> It is a good balance between simplicity and similarity with the libsc, considering the peculiarities  of p4est (e.g. 2 or 3 dimensions, etc.)

Cool!  CMake has its own way of defining enable p4est, p6est, p8est.  Do the
examples compile in all combinations?

**Comment by mkirilin** [comment]
> Cool!  CMake has its own way of defining enable p4est, p6est, p8est.  Do the
> examples compile in all combinations?

Yes, I've tried all the 4 combinations of p6est / p8est and it works well.

**Pull request merged**
