### PR TITLE
Fix -Wstrict-prototypes

### PR DESCRIPTION
**Pull request by prj-**
```warning: a function declaration without a prototype is deprecated in all versions of C```

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks! Can you please add a file doc/author_<lastname>.txt releasing your code under Free BSD?

**Comment by prj-** [comment]
What is this https://github.com/cburstedde/p4est/actions/runs/4599226548?

**Comment by cburstedde** [comment]
> What is this https://github.com/cburstedde/p4est/actions/runs/4599226548?

We had an unrelated merge issue. I'm just now checking your PR against the updated master.

**Comment by cburstedde** [comment]
You might as well merge the current master into this PR and push the merge commit on top.
I'm expecting this to run cleanly.

**Comment by prj-** [comment]
Sure, I'll rebase and force push.

**Comment by prj-** [comment]
Done.

**Comment by cburstedde** [comment]
Thanks so much! I appreciate checking the code with strict compiler flags.

**Comment by prj-** [comment]
You are very welcome. Now you only need to get the Valgrind stuff sorted out and we will be able to use this official repository instead of Toby’s fork inside PETSc.

**Pull request merged**
