### PR TITLE
add test_mesh_corners3.c

### PR DESCRIPTION
**Pull request by scottaiton**
Here's the test program that @hannesbrandt requested, which demonstrates the missing corner information I'm running into with p8est_mesh.

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks! Can I ask you to add a file doc/author_aiton.txt like the others to release your code under BSD? We'll take care updating the Makefiles then.

**Comment by hannesbrandt** [comment]
We discuss potential changes to the `p8est_mesh_t` regarding the edge-hanging corner neighbors in https://github.com/cburstedde/p4est/issues/244.

**Comment by cburstedde** [comment]
Thanks, if I may just ask to format the test program according to our customs (e. g. indentation, no declarations after code within a block) and slightly beyond (liberally adding comments every couple lines explaining what's going on).

**Comment by hannesbrandt** [comment]
Yes, I'll work on this.
During my work on PR https://github.com/cburstedde/p4est/pull/262 I also implemented an inter-tree test case that checks the implementation of edgehanging corner neighbors across tree faces and edges. I would propose to add this to the PR as well.

**Comment by cburstedde** [comment]
> Yes, I'll work on this.
> During my work on PR https://github.com/cburstedde/p4est/pull/262 I also implemented an inter-tree test case that checks the implementation of edgehanging corner neighbors across tree faces and edges. I would propose to add this to the PR as well.

Sounds perfect!

**Comment by cburstedde** [comment]
Thanks! Sorry for being obnoxious, but I'd caution against using TRUE variables in general. It is too tempting to compare == TRUE, which would be wrong. I'm fine with assigning = FALSE or = 0  or = !FALSE or = 1, which is legal.

**Comment by cburstedde** [comment]
Nice thanks so much!

**Pull request merged**
