### PR TITLE
Function to check for shared corners

### PR DESCRIPTION
**Pull request by gghosh8495**
Proposal for a function to check if two related quadrants have common corners.

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks; please use the optimized calculation we talked about offilne.

**Comment by cburstedde** [comment]
With our recent merges, there are now conflicts probably due to white space at the end of the file. In the updated version coming up, it should be possible to provide a conflict-free diff.

**Comment by cburstedde** [comment]
Thanks! Looks nice.

Just a style/convention comment: in the .h files, we usually have the face functions before the corner functions. We also have one empty line between the end of one prototype and the documentation of the next one. Would you be able to make these modifications?

**Comment by gghosh8495** [comment]
@cburstedde Would you like to have any more changes ?

**Comment by cburstedde** [comment]
Thanks, looks good, I just made one tiny swap on top of it.

**Pull request merged**
