### PR TITLE
Feature cmake valgrind

### PR DESCRIPTION
**Pull request by gghosh8495**

### CODE REVIEW

**Comment by gghosh8495** [comment]
@cburstedde By default CMake in p4est creates a static library so I don't think anything extra needs to be done.

**Comment by cburstedde** [comment]
Thanks; I'm getting on the CI page:

No files were found with the provided path: ./Testing/Temporary/. No artifacts will be uploaded

**Comment by gghosh8495** [comment]
I observed that when the memcheck passes the files are empty. Maybe the CI does not do upload blank chunks of memory.

**Comment by cburstedde** [comment]
> I observed that when the memcheck passes the files are empty. Maybe the CI does not upload blank chunks of memory. I believe data is written to files only when leaks are detected.

Thanks, could you please verify this  supposition?

**Comment by gghosh8495** [comment]
@cburstedde The memcheck logs are now uploaded correctly. The path needed to be changed.

**Comment by cburstedde** [comment]
Thanks; I've used this PR to integrate a couple small updates.

**Pull request merged**
