### PR TITLE
Feature valgrind petsc

### PR DESCRIPTION
**Pull request by cburstedde**
# Merge and update valgrind cleanliness

Following up on issue #191.

@tisaac had implemented initializing quadrant arrays and mempools to -1 bits by default. This serves to establish valgrind cleanliness, since quadrants are sometimes copied by struct assignment, which leads to valgrind warnings if not all padding bits have been written to before. This was on a topic branch since last fall.

@tim-griesbach has merged the latest master into that branch and resolved conflicts.

@cburstedde eliminated unnecessary initializations by introducing helper functions and updating the library.

### CODE REVIEW

**Comment by prj-** [comment]
Here is the corresponding PETSc job: https://gitlab.com/petsc/petsc/-/jobs/4057000982.

**Comment by prj-** [comment]
The job is clean, I hope this can get merged. Thanks!

**Review by hannesbrandt — DISMISSED** [review]

**Comment by cburstedde** [comment]
Thanks a lot for bringing this up and testing it!

**Comment by prj-** [comment]
Thank you, I will now get this integrated in PETSc so that Toby does not have to make sure his fork is up-to-date.

**Pull request merged**
