### PR TITLE
Fix CMake build

### PR DESCRIPTION
**Pull request by ligazetom**
# CMake build

Following up on issue with CI for CMake #31

Proposed changes:
Add preprocessor macro.

### CODE REVIEW

**Comment by cburstedde** [comment]
Cool thanks. I haven't compiled ascii VTK since forever.

Btw I like your work. In forestclaw I've written the VTK output to create one giant MPI I/O .vtu file using appended binary data. Would you be interested in backporting something like this to p4est, activated by setting a context property?

**Comment by ligazetom** [comment]
Ah great. This is something I've wanted to do as well, but did not really feel like going that deep. I've just created separate directories for every task and animations.

Since I believe the main logic is already there, it shouldn't be too much of a hassle :) Just point me to the implementation.

**Comment by cburstedde** [comment]
> Ah great. This is something I've wanted to do as well, but did not really feel like going that deep. I've just created separate directories for every task and animations.
> 
> Since I believe the main logic is already there, it shouldn't be too much of a hassle :) Just point me to the implementation.

https://github.com/ForestClaw/forestclaw (Look for the VTK output).

I'm thinking to keep the p4est defaults exactly as is.  Add:

p4est_vtk_context_set_append (int understood as bool, default 0)

to activate the MPI I/O out into one big file.
We'd ignore the P4EST_VTK_BINARY and COMPRESSION macros in this case.
When P4EST_ENABLE_MPIIO is not defined, always assume append = 0
and do not compile the new MPI I/O code.

**Comment by ligazetom** [comment]
I'll have a look in the near future.

**Pull request merged**
