### PR TITLE
Feature make install

### PR DESCRIPTION
**Pull request by cburstedde**
# Update autotools make install mechanism

Following up on issue #204 and prior work.

Proposed changes: Building on libsc configure logic we have three options to link to libsc:

 1. `--with-sc=no` (default) use the source submodule in directory `sc`.
 2. `--with-sc=external` expect necessary compile and link flags in environment variables.
 3. `--with-sc=path` expect a `make install`'d libsc in `path` with subdirectories `lib`, `include`, `share/aclocal`.

What's remaining to do is to allow for different library and include paths, e.g. `--with-sc-lib=libpath` etc.

### CODE REVIEW

**Comment by cburstedde** [comment]
This PR pulls in the top commit of https://github.com/cburstedde/libsc/pull/114.
Comments @jmark, @sloede, @tim-griesbach, @hannesbrandt?

**Comment by sloede** [comment]
> What's remaining to do is to allow for different library and include paths, e.g. `--with-sc-lib=libpath` etc.

Was this supported before? And if not, is this requested by a user currently?

If both answers are no, I am not sure the extra effort is necessary - at least I have never installed anything in a "split" prefix, and thus never needed to specify the paths separately.

Either way, the proposed approach sounds good to me 👍

**Comment by cburstedde** [comment]
> > What's remaining to do is to allow for different library and include paths, e.g. `--with-sc-lib=libpath` etc.
> 
> Was this supported before? And if not, is this requested by a user currently?

No, I'm just thinking ahead.

> If both answers are no, I am not sure the extra effort is necessary - at least I have never installed anything in a "split" prefix, and thus never needed to specify the paths separately.

That's a good point, keeping it simple for now. I was thinking of package maintainers but have not been approached.

> Either way, the proposed approach sounds good to me +1

Thanks for checking!

**Comment by jmark** [comment]
> This PR pulls in the top commit of [cburstedde/libsc#114](https://github.com/cburstedde/libsc/pull/114). Comments @jmark, @sloede, @tim-griesbach, @hannesbrandt?

I successfully compiled this PR with https://github.com/cburstedde/libsc/pull/114 as submodule.

But `libp4est.so` still does not point to `libsc.so` not fixing the issue https://github.com/cburstedde/p4est/issues/204.

**Comment by cburstedde** [comment]
When I configure libsc into some --prefix and do make install, and then configure p4est --with-sc=that install and some --prefix, and make install p4est into that prefix, I get

    $ ldd lib/libp4est.so
    > ...
    > libsc.so.2 => /home/.../lib/libsc.so.2 (0x00007f8374a4e000)
    > ...

How can I reproduce your issue?

**Comment by cburstedde** [comment]
> > This PR pulls in the top commit of [cburstedde/libsc#114](https://github.com/cburstedde/libsc/pull/114). Comments @jmark, @sloede, @tim-griesbach, @hannesbrandt?
> 
> I successfully compiled this PR with [cburstedde/libsc#114](https://github.com/cburstedde/libsc/pull/114) as submodule.
> 
> But `libp4est.so` still does not point to `libsc.so` not fixing the issue #204.

You're right -- typo it libsc commit! Fixed and checking. :)

**Comment by jmark** [comment]
> When I configure libsc into some --prefix and do make install, and then configure p4est --with-sc=that install and some --prefix, and make install p4est into that prefix, I get
> 
> ```
> $ ldd lib/libp4est.so
> > ...
> > libsc.so.2 => /home/.../lib/libsc.so.2 (0x00007f8374a4e000)
> > ...
> ```
> 
> How can I reproduce your issue?

I compiled without `--with-sc`. I did not expect a different linking behavior.

**Comment by jmark** [comment]
> > > This PR pulls in the top commit of [cburstedde/libsc#114](https://github.com/cburstedde/libsc/pull/114). Comments @jmark, @sloede, @tim-griesbach, @hannesbrandt?
> > 
> > 
> > I successfully compiled this PR with [cburstedde/libsc#114](https://github.com/cburstedde/libsc/pull/114) as submodule.
> > But `libp4est.so` still does not point to `libsc.so` not fixing the issue #204.
> 
> You're right -- typo in libsc commit! Fixed and checking. :)

Now it works! Thx!

**Comment by cburstedde** [comment]
> > Comments @jmark, @sloede, @tim-griesbach, @hannesbrandt?
> 
> This looks good to @tim-griesbach and me!

Thanks!

> What do you think about naming the default option a bit more explicitly, for example `--with-sc=submodule` or `--with-sc=internal`?

This is a nice idea, but most packages use the defaults "yes" and "no."

**Comment by jmark** [comment]
I tested this PR together with https://github.com/DLR-AMR/t8code/pull/506 and everything works as expected.

From my side this PR can be merged as soon as possible.

@cburstedde @sloede

**Comment by jmark** [comment]
With this PR I could finally register an official [t8code_jll](https://juliahub.com/ui/Packages/t8code_jll/6PmXJ/1.1.2+2) Julia package. But this is only a temporary solution, since this builds on pre-releases and branches of sc, p4est and t8code. If this PR will be merged in the near future, the package could be build upon official releases of the three libraries.

@cburstedde @tim-griesbach @hannesbrandt @sloede

**Comment by jmark** [comment]
@hannesbrandt @cburstedde Any progress on this PR?

**Comment by cburstedde** [comment]
Thanks @jmark; let's get to this one soon.

**Pull request merged**
