### PR TITLE
lock mpisize to 2 for tests

### PR DESCRIPTION
**Pull request by gghosh8495**

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks; I'd prefer to leave Ncpu unchanged, since it's information from the system (see cmake/config.cmake), and rather add a new variable that is 1 or 2 depending on the available number of cores.

**Comment by gghosh8495** [comment]
@cburstedde I added MPIEXEC_NUMPROC_MAX variable which is the same as in libsc, it is only set to 2 if MPI is activated.

**Comment by cburstedde** [comment]
The numprocs_max variable may best be set in config.cmake, where Ncpu is set, since there is an if condition whether the available number of processes is less than 2, in which case numprocs_max should be 1, not 2.

**Comment by cburstedde** [comment]
I've made this change and am now merging.

**Pull request merged**
