### PR TITLE
indentation and C89 style variable declaration

### PR DESCRIPTION
**Pull request by gghosh8495**
# Title

Following up on issue # 133 .

Proposed changes:
Declare variables conforming to the old C89 compilers.

### CODE REVIEW

**Comment by cburstedde** [comment]
Thanks, could you please separate into two commits, where the first moves the variable declaration and the second does the indentation?

**Comment by gghosh8495** [comment]
Sure

**Comment by cburstedde** [comment]
No need to close, force-push would do it I think. Thanks!

**Comment by gghosh8495** [comment]
I force-pushed, it automatically closed.

**Pull request closed without merging**
