### PR TITLE
update p4est cmake

### PR DESCRIPTION
**Pull request by gghosh8495**
# Title

Following up on issue # .

Proposed changes:

### CODE REVIEW

**Comment by gghosh8495** [comment]
I am unsure of the #cmakedefine comments, I thought it was written as ' define to 1 ' but it looks different. Just to confirm, we are supposed to write it as ' define to 1 ' right ?

**Comment by cburstedde** [comment]
Yes, this time it's ok to align the comments with the usual form "Define to 1" (when in doubt, stay close to the comments created by autoconf).

Can you please enable and check the version test with cmake?

**Comment by gghosh8495** [comment]
@cburstedde Do we need to add an equivalent (P4EST_CXX \"${MPI_CXX_COMPILER}\") in libsc ? This exists in the config.cmake file.

**Comment by gghosh8495** [comment]
@cburstedde I think all cmake files in p4est and libsc have all that is required. There will be a diff because both requires check which are specific to the package.

**Comment by gghosh8495** [comment]
@cburstedde Ready to merge!

**Comment by cburstedde** [comment]
Thanks!

**Pull request merged**
