### PR TITLE
Rename example dir balance_seeds to balance

### PR DESCRIPTION
**Pull request by cburstedde**
# Rename example balance_seeds to balance

The example directory balance_seeds contains a specific balance test. To add further balance tests in the future, it will be more fitting to rename the directory plainly to balance.

### CODE REVIEW

**Comment by cburstedde** [comment]
Asking @mkirilin: does CMake build all example exactly as the autotools do it?

**Comment by mkirilin** [comment]
@cburstedde 
CMake doesn't build examples. Neither during p4est build nor by manual build call for the examples. At the latter case it stops configuring with the error:

```
-- Could NOT find SC (missing: SC_DIR)
CMake Error at /opt/software/easybuild/software/CMake/3.23.1-GCCcore-11.3.0/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SC (missing: SC_LIBRARY SC_INCLUDE_DIR SC_mpi_ok)
Call Stack (most recent call first):
  /opt/software/easybuild/software/CMake/3.23.1-GCCcore-11.3.0/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/kirilin/p4est_workspace/p4est/cmake/FindSC.cmake:66 (find_package_handle_standard_args)
  CMakeLists.txt:26 (find_package)
```

**Comment by pkestene** [comment]
@mkirilin 

Just FYI.
currently, the way cmake has been setup in `example` folder, examples are treated as a separated cmake project; so when you build p4est, examples are not built. One has to build p4est examples separated taking care of providing build information about where p4est libs where installed.

here is what I do to build both p4est and p4est examples with cmake:
```shell
# 1. build p4est
cd $(P4EST_SRC)
mkdir -p _build/cmake
cd _build/cmake
cmake ../..
make; make install
# you should have a folder "local" where both p4est and libsc were just installed
# 2. now build p4est examples using p4est install in "local"
mkdir examples
cd examples
cmake -DCMAKE_PREFIX_PATH=`pwd`/../local ../../../example
make
```

For me building the p4est example works fine; it just a bit "convoluted" because examples are in separated cmake project. It should be documented somewhere.

**Comment by cburstedde** [comment]
Thanks for the summary!

Personally I'd rather simplify and have the examples built together with the
library.  The separate project would no longer be necessary.  How hard would
it be to do it this way (which is also the autotools way)?

> currently, the way cmake has been setup in `example` folder, examples are treated as a separated cmake project; so when you build p4est, examples are not built. One has to build p4est examples separated taking care of providing build information about where p4est libs where installed.
> 
> here is what I do to build both p4est and p4est examples with cmake:
> ```shell
> # 1. build p4est
> cd $(P4EST_SRC)
> mkdir -p _build/cmake
> cd _build/cmake
> cmake ../..
> make; make install
> # you should have a folder "local" where both p4est and libsc were just installed
> # 2. now build p4est examples using p4est install in "local"
> mkdir examples
> cd examples
> cmake -DCMAKE_PREFIX_PATH=`pwd`/../local ../../../example
> make
> ```
> 
> For me building the p4est example works fine; it just a bit "convoluted" because examples are in separated cmake project. It should be documented somewhere.

**Comment by pkestene** [comment]
Should'nt be hard. I'll look it.

**Comment by cburstedde** [comment]
I'll merge this now to continue with the proper directory structure.

**Pull request merged**
