### PR TITLE
Instruction for Windows build and linking with MS Visual Studio

### PR DESCRIPTION
**Pull request by mike-matveev**
Instructions for Windows build using MSYS2/MinGW64 toolchain.

### CODE REVIEW

**Comment by cburstedde** [comment]
Mike, this is great. We could add a --enable-windows configure option. By your suggestions, it would
* enable the changes to the source code
* add make targets to create the dll/lib files.
I can add the first part, but for the second I'd rely on your testing. Do you want to give it a shot?

**Comment by mike-matveev** [comment]
Carsten, ok, I will try to do it but cannot promise it is going to be very soon. Also, please note that this effectively kills all the multi-thread features of the library.

**Comment by cburstedde** [comment]
Cool, whenever you get to it -- you could make your windows build crash with --enable-pthread or --enable-openmp. Without these flags it should work (no threading used then).

**Comment by cburstedde** [comment]
Please create pull requests against develop next time.
Thanks and merged.

**Pull request merged**
